export const biomeDescriptors = [
  "[REDACTED]",
  "Abandoned",
  "Acidic",
  "Acrid",
  "Airless",
  "Arctic",
  "Arid",
  "Ash-Shrouded",
  "Ashen",
  "Azure",
  "Barren",
  "Basalt",
  "Bladed",
  "Bleak",
  "Blighted",
  "Blood",
  "Boggy",
  "Boiling",
  "Boiling Doom",
  "Bountiful",
  "Breached",
  "Bubbling",
  "Cabled",
  "Calcified",
  "Capped",
  "Caustic",
  "Caustic Nightmare",
  "Cerulean",
  "Charred",
  "Chromatic Fog",
  "Cloudy",
  "Columned",
  "Contaminated",
  "Corrosive",
  "Corrupted",
  "Contoured",
  "Crimson",
  "Damp",
  "Dead",
  "Deathly Green Anomaly",
  "Decaying Nuclear",
  "Desert",
  "Desolate",
  "Doomed",
  "Doomed Jade",
  "Dusty",
  "Empty",
  "Endless Morass",
  "Erased",
  "Erupting",
  "Fiery",
  "Fiery Dreadworld",
  "Finned",
  "Fissured",
  "Flame-Ruptured",
  "Flourishing",
  "Foaming",
  "Foggy",
  "Forsaken",
  "Fractured",
  "Fragmented",
  "Freezing",
  "Frostbound",
  "Frothing",
  "Frozen",
  "Frozen Anomaly",
  "Frozen Hell",
  "Fungal",
  "Gamma-Intensive",
  "Glacial",
  "Glassy",
  "Grassy",
  "Harsh Blue Globe",
  "Haunted Emeril",
  "Hazy",
  "Hexagonal",
  "Hiemal",
  "High Energy",
  "High Radio Source",
  "High Temperature",
  "Hot",
  "Humid",
  "Hyperborean",
  "Icebound",
  "Icy",
  "Icy Abhorrence",
  "Imminent Core Detonation",
  "Incandescent",
  "Infected",
  "Infected Dustbowl",
  "Infested",
  "Infested Paradise",
  "Irradiated",
  "Isotopic",
  "Lava",
  "Life-Incompatible",
  "Lifeless",
  "Lost Blue",
  "Lost Green",
  "Lost Red",
  "Low Atmosphere",
  "Magma",
  "Malfunctioning",
  "Marshy",
  "Mechanical",
  "Metallic",
  "Metallurgic",
  "Miasmatic",
  "Misty",
  "Molten",
  "Murky",
  "Mutated",
  "Noxious",
  "Nuclear",
  "Obsidian Bead",
  "of Light",
  "Ossified",
  "Overgrown",
  "Paradise",
  "Parched",
  "Petrified",
  "Pillared",
  "Planetary Anomaly",
  "Plated",
  "Poisonous",
  "Quagmire",
  "Radioactive",
  "Radioactive Abomination",
  "Rainy",
  "Rattling",
  "Reeking",
  "Rocky",
  "Rotting",
  "Scalding",
  "Scaly",
  "Scarlet",
  "Scorched",
  "Sharded",
  "Shattered",
  "Shell-Strewn",
  "Skeletal",
  "Spined",
  "Sporal",
  "Stellar Corruption Detected",
  "Sub-zero",
  "Supercritical",
  "Swamp",
  "Tainted",
  "Tectonic",
  "Temperate",
  "Temporary",
  "Terraforming Catastrophe",
  "Terrorsphere",
  "The Nest",
  "Thirsty",
  "Torrid",
  "Toxic",
  "Toxic Anomaly",
  "Toxic Horror",
  "Tropical",
  "Ultramarine",
  "Unstable",
  "Vapour",
  "Verdant",
  "Vermillion Globe",
  "Vile Anomaly",
  "Violent",
  "Viridescent",
  "Volcanic",
  "Webbed",
  "Wind-swept",
  "Wine Dark",
  "Worm-Ridden",
  "Xeno-Colony",
];

export const sharedDescriptors = [
  "Abandoned",
  "Desolate",
  "Corrupted",
  "Infested",
  "Tropical",
];

export const specialDescriptors = [
  "Terraforming Catastrophe",
  "Imminent Core Detonation",
  "Infested Paradise",
  "Xeno-Colony",
  "The Nest",
  "Toxic Horror",
  "Caustic Nightmare",
  "Boiling Doom",
  "Fiery Dreadworld",
  "Radioactive Abomination",
  "Icy Abhorrence",
  "Frozen Hell",
  "Infected Dustbowl",
  "Terrorsphere",
  "Planetary Anomaly",
  "Stellar Corruption Detected",
  "Vermillion Globe",
  "Vile Anomaly",
  "Harsh Blue Globe",
  "Toxic Anomaly",
  "Deathly Green Anomaly",
  "Frozen Anomaly",
];

export const biomes = [
  "Barren",
  "Beams",
  "Bone Spire",
  "Bubble",
  "Chromatic",
  "Contour",
  "Dead",
  "Fract Cube",
  "Frozen",
  "Glitch",
  "Hexagon",
  "Hydro Garden",
  "Infested Barren",
  "Infested Frozen",
  "Infested Irradiated",
  "Infested Lush",
  "Infested Scorched",
  "Infested Toxic",
  "Irradiated",
  "Irri Shells",
  "Lush",
  "M Structure",
  "Marsh",
  "Scorched",
  "Shards",
  "Toxic",
  "Volcanic",
  "Wire Cell",
];

export const exoticBiomes = [
  "Beams",
  "Bone Spire",
  "Bubble",
  "Chromatic",
  "Contour",
  "Fract Cube",
  "Glitch",
  "Hexagon",
  "Hydro Garden",
  "Irri Shells",
  "M Structure",
  "Shards",
  "Wire Cell",
];

export const agriculturalResources = [
  "None",
  "Cactus Flesh",
  "Frost Crystal",
  "Fungal Mould",
  "Gamma Root",
  "Solanium",
  "Star Bulb",
];

export const stellarMetals = [
  "Copper",
  "Activated Copper",
  "Cadmium",
  "Activated Cadmium",
  "Emeril",
  "Activated Emeril",
  "Indium",
  "Activated Indium",
];

export const localResources = [
  "Ammonia",
  "Basalt",
  "Dioxite",
  "Faecium",
  "Gold",
  "Mordite",
  "Paraffinium",
  "Phosphorus",
  "Pyrite",
  "Rusted Metal",
  "Uranium",
];

export const generalResources = [
  "Cobalt",
  "Magnetized Ferrite",
  "Salt",
  "Silver",
  "Sodium",
];
